# Author: Meng Wang
# Date: 19-05-2017
# configuration file for phue_api honeypot. This is for making a lot of different JID listen together to wait for scans.
 names:
    - smart-home-monitor
    - sensor-monitor
    - light
 domains:
    - xmpp.jp
    - jabber.at
    - 4ept.net
    - chatme.im
    - jabber.network
    - chinwag.im
    - movim.eu
 resources:
    - temperature
    - light
    - light1
    - light2
    - bri
